config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home, only: [:index]

  resources :text_files
  resources :pictures
end

app/models/file_picker_module.rb
require 'rest_client'

module FilePickerModule

  def self.upload_picture(attachment)
    types = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
    result = FilePickerModule.upload attachment
    if types.include? result[:type]
      result
    else
      FilePickerModule.delete result[:url]
      { error: "Invalid format. Only these types are supported: #{types}" }
    end
  end

  def self.upload_text_file(attachment)
    result = FilePickerModule.upload attachment
    if result[:type] == 'text/plain'
      result
    else
      FilePickerModule.delete result[:url]
      { error: "Invalid format. Only text files are supported" }
    end
  end

  def self.delete(url)
    final_url = url[0...8] + "www" + url[11...url.length]
    RestClient.delete "#{final_url}?key=#{$filepicker_api_key}"
  end

  private
    def self.upload(file_input)
      # Upload file
      remote_url = "#{$filepicker_root}/store/S3?key=#{$filepicker_api_key}"
      response = RestClient.post remote_url, fileUpload: file_input
      jsonResponse = JSON.parse(response)
      url = jsonResponse['url']
      filename = jsonResponse['filename']
      type = jsonResponse['type']

      {url: url, filename: filename, type: type }
    end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :name, presence: true

  scope :by_name, -> { order(:name) }
  scope :by_date, -> { order(updated_at: :desc) }

  def as_json(options = {})
    hash = super.as_json options
    hash[:attachment] = {url: attachment}
    hash
  end
end

app/models/text_file.rb
class TextFile < ActiveRecord::Base
  validates :name, presence: true

  scope :by_name, -> { order(:name) }
  scope :by_date, -> { order(updated_at: :desc) }

  def as_json(options = {})
    hash = super.as_json options
    hash[:attachment] = {url: attachment}
    hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  include FilePickerModule

  def index
    @pictures = Picture.by_date.by_name

    respond_to do |f|
      f.html
      f.json { render json: @pictures, status: :ok }
    end
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture      = Picture.new
    upload = FilePickerModule.upload_picture picture_params[:attachment]

    if upload.has_key? :error
      @error = upload[:error]
      render 'new'
    else
      @picture.name = upload[:filename]
      @picture.attachment = upload[:url]
      @picture.save
      redirect_to pictures_path
    end
  end

  def destroy
    @picture = Picture.find params[:id]
    FilePickerModule.delete @picture.attachment
    @picture.destroy
    redirect_to pictures_path
  end

  private
  def picture_params
    params.require(:picture).permit(:attachment)
  end
end

app/controllers/text_files_controller.rb
class TextFilesController < ApplicationController

  include FilePickerModule

  def index
    @files = TextFile.by_date.by_name

    respond_to do |f|
      f.html
      f.json { render json: @files, status: :ok }
    end
  end

  def new
    @file = TextFile.new
  end

  def create
    @file      = TextFile.new
    upload = FilePickerModule.upload_text_file text_file_params[:attachment]

    if upload.has_key? :error
      @error = upload[:error]
      render 'new'
    else
      @file.name = upload[:filename]
      @file.attachment = upload[:url]
      @file.save
      redirect_to text_files_path
    end
  end

  def show
    @file = TextFile.find(params[:id])

    respond_to do |f|
      f.html
      f.json { render json: @file, status: :ok }
    end
  end

  def destroy
    @file = TextFile.find params[:id]
    FilePickerModule.delete @file.attachment
    @file.destroy
    redirect_to text_files_path
  end

  private
  def text_file_params
    params.require(:text_file).permit(:name, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.homepage
  %p
    = link_to 'Text Files', text_files_path

  %p
    = link_to 'Pictures', pictures_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DownthereServer</title>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="main-wrapper">
  <%= yield %>
</div>
</body>
</html>

app/views/pictures/index.html.haml
.list
  .upload-wrapper
    =  link_to 'Upload a new picture', new_picture_path

  %ul.pictures
    - @pictures.each do |p|
      %li
        = image_tag(p.attachment)
        .details
          %p.filename= p.name
          %p= "#{time_ago_in_words(p.updated_at)} ago"
          = button_to 'Delete', p, method: :delete, class: 'delete-button'

app/views/pictures/new.html.haml
.upload-form
  %h1 Upload a new picture

  - unless @error.nil?
    %p.error=@error

  = form_for @picture, html: {multipart: true } do |f|
    %p
      = f.file_field :attachment, class: 'attachment-button'
    %p.right
      = f.submit "Save", class: 'save-button'

app/views/text_files/index.html.haml
.list
  .upload-wrapper
    = link_to 'Upload a new file', new_text_file_path

  %ul.files
    - @files.each do |f|
      %li
        .details
          %p.filename= f.name
          %p= "#{time_ago_in_words(f.updated_at)} ago"
          %p= link_to 'Download', f.attachment, class: 'download-button', download: 'download'
          = button_to 'Delete', f, method: :delete, class: 'delete-button'

app/views/text_files/new.html.haml
.upload-form
  %h1 Upload a new text file

  - unless @error.nil?
    %p.error=@error

  = form_for @file, html: {multipart: true } do |f|
    %p
      = f.file_field :attachment, class: 'attachment-button'
    %p.right
      = f.submit "Save", class: 'save-button'